name: Deploy to GitHub pages

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Init new repo in site folder and commit static files
        run: |
          rm -rf .git
          git init
          rm README.md
          mv site/* .
          git add -A
          git config --local user.email "vmeca87@gmail.com"
          git config --local user.name "Victor Cabello"
          git config --global --add safe.directory '*'
          git commit -m 'deploy'

      - name: Force push to destination branch
        uses: ad-m/github-push-action@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          force: true
          directory: ./
